In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("insurance_data.csv")
df.shape

(1340, 11)

In [3]:
df.head()

,index,PatientID,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,0,1,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,1,2,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,2,3,NaN,male,33.3,82,Yes,0,No,southeast,1135.94
3,3,4,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,4,5,NaN,male,34.1,100,No,0,No,northwest,1137.01

In [4]:
df.dropna(inplace= True)

In [5]:
df.isnull().sum()

index            0
PatientID        0
age              0
gender           0
bmi              0
bloodpressure    0
diabetic         0
children         0
smoker           0
region           0
claim            0
dtype: int64

In [9]:
x = df[['age','bmi','bloodpressure','children']]
y = df['claim']

x.head()

    age   bmi  bloodpressure  children
0  39.0  23.2             91         0
1  24.0  30.1             87         0
7  19.0  41.1            100         0
8  20.0  43.0             86         0
9  30.0  53.1             97         0

       age   bmi  bloodpressure  children
0     39.0  23.2             91         0
1     24.0  30.1             87         0
7     19.0  41.1            100         0
8     20.0  43.0             86         0
9     30.0  53.1             97         0
...    ...   ...            ...       ...
1335  44.0  35.5             88         0
1336  59.0  38.1            120         1
1337  30.0  34.5             91         3
1338  37.0  30.4            106         0
1339  30.0  47.4            101         0

[1332 rows x 4 columns]

# Train Test split

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train , y_test = train_test_split(x,y,test_size = 0.2, random_state=2)

In [13]:
x_train.shape

(1065, 4)

# Model code

In [12]:
from sklearn.linear_model import LinearRegression

mlr = LinearRegression()

In [14]:
mlr.fit(x_train,y_train)

LinearRegression()

In [16]:
y_pred = mlr.predict(x_test)
y_pred

array([18549.11982971, 15211.59447123, 11958.55300448, 16995.97533928,
       10803.9581797 , 11187.73270299, 34567.85098672, 11410.29149795,
       11771.60156847,  5911.51531281, 12601.51758122, 11178.26993061,
        6142.48951258, 10077.3100568 ,  8287.16323563, 10693.89528278,
       19829.7567638 , 15674.33653233,  8078.53209259, 16915.61685235,
        6020.0228265 ,  5834.72709468,  6763.94531615, 12289.1152431 ,
       13970.06378721, 10701.07841451,  5219.75105624, 13866.03949125,
       31696.52914077, 19847.70176791,  9207.23587565, 10272.33331606,
       16471.01514629, 19886.30849873,  9113.30634098, 13217.04815198,
        8571.24408353, 13280.0469228 ,  8646.5293543 ,  9821.17833394,
        7148.0488688 , 13201.97733773, 25141.69819851,  9082.78779802,
        4612.95308123, 13179.0620156 ,  8370.75432903, 13152.58310868,
        6279.97320861, 22671.4469459 , 10884.60112833,  7238.8546144 ,
        7216.92712057,  9431.1521257 , 12047.82230868, 13875.88175529,
       20334.05188807, 14966.46453936,  6030.73089457, 16368.21070445,
       12106.381061  , 21763.97723195, 14111.09804542, 12718.74842943,
       17845.69043245, 17887.74225008, 15369.39784199, 17158.18720807,
        8998.55898076,  7617.98450703, 12035.19238832, 28726.06815177,
        8014.45775116,  7536.3945118 ,  8051.7103689 , 16601.82372626,
        4861.95805387, 11126.92369725,  6755.92653241, 11389.75418845,
        9082.02231494,  4526.80498889, 28151.98774602,  5026.80300974,
       13445.74981451, 13796.40304405,  3361.28188407, 19788.50786894,
        9319.70101801, 17210.15480067, 12906.76951683,  7359.266398  ,
        8215.60751337, 12101.96922096, 15100.87748582, 15443.11394211,
       21136.94611575,  6475.8918434 ,  4750.34432449,  8636.52446857,
       11048.63981942, 29436.78023692, 14349.1104883 , 14094.08114608,
       36433.85457924, 26685.73788918,  3207.95718026, 15697.35004217,
       13284.94115267,  6017.48690263, 13115.2944197 ,  7839.74037922,
       33921.42238134, 12622.42451751, 11795.35588461, 35808.51781569,
       18921.15904337,  8991.09138734,  8166.76447464,  5710.56347874,
       13846.13082865, 25676.10479925, 10323.28292833,  6533.67448298,
       13198.74396647,  7384.07400092, 20514.9685091 , 12164.21750489,
       17586.60919638,  2925.3629151 , 15317.47360829, 19164.50885384,
       15498.99522394, 13941.36477891, 13407.10701244, 16888.57354823,
       16564.75267205,  3855.50924134, 12431.02456658,  5823.29929538,
        9352.68668435, 13197.31376524, 11885.14107267, 14656.36746774,
       10382.7108267 , 12286.07919635,  4525.13034288,  9590.08821339,
       13103.79053225,  8105.28243859, 31290.91365721,  8237.62411795,
       10887.95633958, 24118.58711725, 20837.81476386, 21336.03839827,
        6922.0260452 ,  7500.60482453, 12735.69181784, 15905.75310504,
       27990.69335234, 16453.0865068 ,  9016.01825304, 10805.41853296,
       31101.30051168, 26725.30879602,  7906.04860945, 20097.86884471,
        8161.65852922, 18449.06045007,  9977.82551976, 10730.6818753 ,
        8163.50171615,  4999.87110022, 16248.47529316, 16174.04674948,
       15297.09557848, 13093.13155804, 20606.8038892 ,  9109.23731771,
        5307.07169814, 13314.92486992, 37839.56429221, 13684.23478235,
       15483.99321018,  7231.51220298, 13989.18983731,  8810.56804539,
       18691.02717961,  5753.41111574,  6817.64256785, 10409.07047084,
       14094.90377547, 12318.65187698, 10220.42286977, 10857.02223372,
       15352.25910265, 29126.34960975, 13913.55780413,  3351.9547391 ,
        8116.3005942 , 10253.88363827, 18713.90506205,  4022.18675447,
       11156.90999172, 13147.52625713,  4204.36837782,  7487.16548166,
       12609.29902356,  8925.07096081,  9188.95473878, 13225.20985078,
       12442.22428571, 16148.30709614, 21998.07006638,  8345.79215688,
        6940.34325332, 32495.10655839, 14235.85621058,  6623.35677288,
       14165.81585465, 16277.3296355 , 13643.71606412, 15002.39577326,
       17800.94341127, 15746.13669938,  6458.97389657,  4051.11976216,
       15179.80834874, 17062.33266337, 14947.19223219, 14416.37955253,
        8200.98241406,  4909.26070555, 12312.40019202, 11271.23134362,
       13517.83444325, 11290.82418373, 14132.74502321, 41888.53448968,
        8751.6185912 , 15611.17256261,  9110.00416923, 16740.41709058,
       27583.50946293, 32387.81358472,  8692.86782996,  8982.26968084,
        9546.81456807, 10390.04989611, 18433.11791257,  6592.6566664 ,
       10533.52189047, 11846.85410999,  9137.89630912, 15090.88896471,
        7527.26863698, 13020.44980286, 15258.30986135,  8779.90795581,
       14518.34165836,  9299.73855111, 18390.98666479,  7184.77710624,
        8974.78572279, 15405.70599034,  7342.37210346])

# accuracy checking

In [17]:
from sklearn.metrics import r2_score

In [18]:
r2_score(y_test, y_pred)

0.3855651755820245